---
# tasks file for snmp
- name: ":::: Determine device type ::::"
  cisco.nxos.nxos_config:
    lines: hostname {{ inventory_hostname }}
    save_when: device_type

- name: ":::: NXOS tasks ::::"
  include_tasks:
    file: nxos_tasks.yaml
  
- name: ":::: Set facts ::::"
  set_fact:
    cisco.nxos.nxos_facts: 
      - gather_network_resources: snmp_servers

- name: ":::: NXOS filter data for comparasion ::::"
  include_tasks:
    file: nxos_filter_comparation.yaml

