---
- name: Install HAProxy, Keepalived, and FreeIPA on a single RHEL 9 node
  hosts: localhost
  become: true
  vars:
    haproxy_backend_servers:
      - name: self
        address: 127.0.0.1
        port: 8080
    keepalived_virtual_ip: 192.168.122.100
    keepalived_interface: eth0
    freeipa_realm: EXAMPLE.LOCAL
    freeipa_domain: example.local
    freeipa_hostname: ipa.example.local
    freeipa_admin_password: Secret123
    freeipa_directory_manager_password: Secret123
  roles:
    - role: haproxy_install
    - role: keepalived_install
    - role: freeipa_install
